### ISSUE TITLE
Plays entire playlist after combat ends

### ISSUE THREAD

**Issue by Perogy** [vadanx/foundryvtt-combat-orchestrator#7]
Thanks for the great module, it almost works perfectly for me. I'm having an issue with combat end music. It's supposed to go back to the track that was previously playing after combat ends, but what it does instead is play the entire playlist from the beginning. So if I have a playlist with all my ambient sound in it (100 or so tracks) it will always just play the first one in the list after combat ends.

Additionally it does not seem to go back to the previously playing song if it was triggered via "scene music" rather than triggered manually.

**Comment by vadanx** [comment]
@Perogy , thank you for the issue! Apologies as I have been away and this is the first time I'm seeing it.

I will try and recreate your issue (should not be hard as I definitely did not write the code to cover your case) and will add support to cover it.

**Comment by vadanx** [comment]
Modules `Vadanx's Combat Orchestrator` and `Vadanx's Common Library` have been updated.

**Comment by Perogy** [comment]
Just updated. Fantastic works great now!

**Comment by vadanx** [comment]
@Perogy , happy to hear it. Feel free to suggest more improvements, bug reports etc.
